/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Input Inventory */
        get: operations["input_inventory_api_v1_input_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/input-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Input Status */
        get: operations["get_run_input_status_api_v1_runs__run_id__input_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Works */
        get: operations["list_works_api_v1_runs__run_id__works_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/works/{work_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Work */
        get: operations["get_work_api_v1_runs__run_id__works__work_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Work */
        patch: operations["patch_work_api_v1_runs__run_id__works__work_id__patch"];
        trace?: never;
    };
    "/api/v1/runs/{run_id}/works/{work_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Work */
        post: operations["approve_work_api_v1_runs__run_id__works__work_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish */
        post: operations["publish_api_v1_runs__run_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open Source File */
        get: operations["open_source_file_api_v1_runs__run_id__source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/exports/{format}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Export */
        get: operations["download_export_api_v1_runs__run_id__exports__format__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Catalog Fields */
        get: operations["list_catalog_fields_api_v1_catalog_fields_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Schemas */
        get: operations["list_schemas_api_v1_catalog_schemas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/schemas/{schema_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schema */
        get: operations["get_schema_api_v1_catalog_schemas__schema_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiRunStatus
         * @description Lifecycle of one local input-folder processing run.
         * @enum {string}
         */
        ApiRunStatus: "queued" | "processing" | "review" | "published" | "failed";
        /** AttentionItemResponse */
        AttentionItemResponse: {
            /** Code */
            code: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "warning" | "error";
            /** Message */
            message: string;
            /** Field Id */
            field_id?: string | null;
            /** Field Label */
            field_label?: string | null;
        };
        /** CandidateResponse */
        CandidateResponse: {
            /** Values */
            values: string[];
            /** Score */
            score: number;
            /** Sources */
            sources: string[];
            /** Methods */
            methods: string[];
        };
        /** CatalogFieldResponse */
        CatalogFieldResponse: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Repeatable */
            repeatable: boolean;
            /** Value Type */
            value_type: string;
        };
        /** FieldDetailResponse */
        FieldDetailResponse: {
            /** Field Id */
            field_id: string;
            /** Label */
            label: string;
            /** Repeatable */
            repeatable: boolean;
            /** Value Type */
            value_type: string;
            /**
             * Requirement
             * @enum {string}
             */
            requirement: "required" | "conditional";
            /** Selected Values */
            selected_values: string[];
            /** Resolution Status */
            resolution_status: string;
            /** Confidence */
            confidence: number;
            /** Reason */
            reason: string;
            /** Selected Sources */
            selected_sources: string[];
            /** Alternatives */
            alternatives: components["schemas"]["CandidateResponse"][];
            /** Rule Summary */
            rule_summary: string;
            /** Rule Details */
            rule_details: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /**
             * Local Only
             * @default true
             */
            local_only: boolean;
            /**
             * Input Mode
             * @default folder
             * @constant
             */
            input_mode: "folder";
            /** Input Directory */
            input_directory: string;
            /** Api Database */
            api_database: string;
            /** Frontend Available */
            frontend_available: boolean;
        };
        /** InputFileChangeResponse */
        InputFileChangeResponse: {
            /** Relative Path */
            relative_path: string;
            /**
             * Change
             * @enum {string}
             */
            change: "added" | "removed" | "modified";
        };
        /** InputFileResponse */
        InputFileResponse: {
            /** Relative Path */
            relative_path: string;
            /** Source Type */
            source_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
        };
        /** InputInventoryResponse */
        InputInventoryResponse: {
            /** Input Directory */
            input_directory: string;
            /** Files */
            files: components["schemas"]["InputFileResponse"][];
            /** Fingerprint */
            fingerprint: string;
            /** Total Bytes */
            total_bytes: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /** PublishResponse */
        PublishResponse: {
            run: components["schemas"]["RunResponse"];
            /** References */
            references: number;
            /** Exports */
            exports: {
                [key: string]: string;
            };
        };
        /**
         * ReferenceReadiness
         * @description Whether a generated reference is safe to present as final.
         * @enum {string}
         */
        ReferenceReadiness: "ready" | "review_required" | "blocked";
        /**
         * ReviewState
         * @description Human review lifecycle used by the local API workflow.
         * @enum {string}
         */
        ReviewState: "pending" | "approved" | "corrected" | "excluded";
        /** RunCreateRequest */
        RunCreateRequest: {
            /** Access Date */
            access_date?: string | null;
            /**
             * Recursive
             * @default true
             */
            recursive: boolean;
            /**
             * Ocr Page Limit
             * @default 2
             */
            ocr_page_limit: number;
            /**
             * First Author Et Al
             * @default false
             */
            first_author_et_al: boolean;
            /**
             * Cache
             * @default true
             */
            cache: boolean;
        };
        /** RunInputStatusResponse */
        RunInputStatusResponse: {
            /** Run Id */
            run_id: string;
            /** Changed */
            changed: boolean;
            /** Expected Fingerprint */
            expected_fingerprint: string;
            /** Current Fingerprint */
            current_fingerprint: string;
            /** Checked At */
            checked_at: string;
            /** Changes */
            changes: components["schemas"]["InputFileChangeResponse"][];
        };
        /** RunResponse */
        RunResponse: {
            /** Run Id */
            run_id: string;
            status: components["schemas"]["ApiRunStatus"];
            /** Created At */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Published At */
            published_at: string | null;
            /** Access Date */
            access_date: string;
            /** Physical Sources */
            physical_sources: number;
            /** Selected Works */
            selected_works: number;
            /** Ready References */
            ready_references: number;
            /** Review Required References */
            review_required_references: number;
            /** Blocked References */
            blocked_references: number;
            /** Excluded Works */
            excluded_works: number;
            /** Revision */
            revision: number;
            /** Error Message */
            error_message: string | null;
        };
        /** SchemaResponse */
        SchemaResponse: {
            /** Id */
            id: string;
            /** Section */
            section: string;
            /** Printed Page */
            printed_page: number;
            /** Label */
            label: string;
            /** Family */
            family: string;
            /** Medium */
            medium: string;
            /** Required Fields */
            required_fields: string[];
            /** Conditional Fields */
            conditional_fields: string[];
            /** Ordered Fields */
            ordered_fields: string[];
            /** Pattern */
            pattern: string;
            /** Notes */
            notes: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkActionResponse */
        WorkActionResponse: {
            run: components["schemas"]["RunResponse"];
            work: components["schemas"]["WorkDetailResponse"];
        };
        /** WorkDetailResponse */
        WorkDetailResponse: {
            /** Work Id */
            work_id: string;
            /** Source File */
            source_file: string;
            /** Source Files */
            source_files: string[];
            /** Source Relative Path */
            source_relative_path: string;
            /** Source Relative Paths */
            source_relative_paths: string[];
            /** Schema Id */
            schema_id: string | null;
            /** Schema Label */
            schema_label: string | null;
            /** Schema Family */
            schema_family: string | null;
            /** Manual Section */
            manual_section: string | null;
            /** Title */
            title: string | null;
            readiness: components["schemas"]["ReferenceReadiness"];
            review_state: components["schemas"]["ReviewState"];
            /** Included */
            included: boolean;
            /** Reference */
            reference: string | null;
            /** Issues */
            issues: string[];
            /** Source Types */
            source_types: string[];
            schema: components["schemas"]["SchemaResponse"] | null;
            /** Fields */
            fields: components["schemas"]["FieldDetailResponse"][];
            /** Missing Required Fields */
            missing_required_fields: string[];
            /** Conflicting Fields */
            conflicting_fields: string[];
            /** Can Approve */
            can_approve: boolean;
            /** Correction Suggestions */
            correction_suggestions: {
                [key: string]: unknown;
            }[];
            /** Attention Items */
            attention_items: components["schemas"]["AttentionItemResponse"][];
            /** Processing Error */
            processing_error: string | null;
        };
        /** WorkPatchRequest */
        WorkPatchRequest: {
            /** Schema Id */
            schema_id?: string | null;
            /** Fields */
            fields?: {
                [key: string]: string | string[] | null;
            };
            /** Included */
            included?: boolean | null;
        };
        /** WorkSummaryResponse */
        WorkSummaryResponse: {
            /** Work Id */
            work_id: string;
            /** Source File */
            source_file: string;
            /** Source Files */
            source_files: string[];
            /** Source Relative Path */
            source_relative_path: string;
            /** Source Relative Paths */
            source_relative_paths: string[];
            /** Schema Id */
            schema_id: string | null;
            /** Schema Label */
            schema_label: string | null;
            /** Schema Family */
            schema_family: string | null;
            /** Manual Section */
            manual_section: string | null;
            /** Title */
            title: string | null;
            readiness: components["schemas"]["ReferenceReadiness"];
            review_state: components["schemas"]["ReviewState"];
            /** Included */
            included: boolean;
            /** Reference */
            reference: string | null;
            /** Issues */
            issues: string[];
            /** Source Types */
            source_types: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    health_api_v1_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    input_inventory_api_v1_input_get: {
        parameters: {
            query?: {
                recursive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InputInventoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_input_status_api_v1_runs__run_id__input_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunInputStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_works_api_v1_runs__run_id__works_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_api_v1_runs__run_id__works__work_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_work_api_v1_runs__run_id__works__work_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                work_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_work_api_v1_runs__run_id__works__work_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_api_v1_runs__run_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_source_file_api_v1_runs__run_id__source_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_export_api_v1_runs__run_id__exports__format__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                format: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_catalog_fields_api_v1_catalog_fields_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogFieldResponse"][];
                };
            };
        };
    };
    list_schemas_api_v1_catalog_schemas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"][];
                };
            };
        };
    };
    get_schema_api_v1_catalog_schemas__schema_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schema_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
